- name: Create Media folder for hosted services
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ media | dict2items }}"

- name: Create Torrents folder for hosted services
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ torrents | dict2items }}"
