- name: Home
  desktop-navigation-width: slim

  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: "Media"
          sites:
            - title: Booklore
              url: ${BASE_URL}:9002
              icon: https://raw.githubusercontent.com/adityachandelgit/BookLore/refs/heads/develop/assets/favicons/android-chrome-512x512.png
            - title: Calibre Web Automated
              url: ${BASE_URL}:9003
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/calibre.svg
            - title: Immich
              url: ${BASE_URL}:2283
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/immich.svg
            - title: Jellyfin
              url: ${BASE_URL}:8096
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/jellyfin.svg
            - title: Jellyseerr
              url: ${BASE_URL}:5055
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/jellyseerr.svg
            - title: Navidrome
              url: ${BASE_URL}:4533
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/navidrome.svg

        - type: monitor
          cache: 1m
          title: "*Arr"
          sites:
            - title: Prowlarr
              url: ${BASE_URL}:9696
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/prowlarr.svg
            - title: Radarr
              url: ${BASE_URL}:7878
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/radarr.svg
            - title: Sonarr
              url: ${BASE_URL}:8989
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/sonarr.svg

        - type: monitor
          cache: 1m
          title: "Services"
          sites:
            - title: Midday
              url: https://midday.radiant.garden
              icon: https://github.com/midday-ai.png
            - title: Nextcloud
              url: https://nextcloud.com/fr/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/nextcloud.svg
            - title: Vaultwarden
              url: https://github.com/dani-garcia/vaultwarden
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vaultwarden.svg

        - type: monitor
          cache: 1m
          title: "Infra"
          sites:
            - title: Duplicati
              url: ${BASE_URL}:8200
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/duplicati.svg
            - title: Ntfy
              url: ${BASE_URL}:9006
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/ntfy.svg
            - title: Tailscale
              url: https://tailscale.com/
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/headscale.svg
            - title: Traefik
              url: ${BASE_URL}:9007
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/traefik.svg

        - type: monitor
          cache: 1m
          title: Downloads
          sites:
            - title: Calibre Web Book Downloader
              url: ${BASE_URL}:9005
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/calibre.svg
            - title: Deluge
              url: ${BASE_URL}:9004
              icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/deluge.svg

    - size: small
      widgets:
        - type: custom-api
          title: Calibre Web
          url: ${CALIBREWEB_URL}/opds/stats
          headers:
            Authorization: Basic ${CALIBREWEB_CREDS_B64}
          template: |
            <div class="flex justify-evenly text-center">
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Int "books" | formatNumber }}</div>
                    <div class="size-h6">Books</div>
                </div>
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Int "authors" | formatNumber }}</div>
                    <div class="size-h6">Authors</div>
                </div>
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Int "series" | formatNumber }}</div>
                    <div class="size-h6">Series</div>
                </div>
                <div>
                    <div class="color-highlight size-h3">{{ .JSON.Int "categories" | formatNumber }}</div>
                    <div class="size-h6">Categories</div>
                </div>
            </div>

        - type: custom-api
          title: Immich stats
          cache: 1d
          url: ${IMMICH_URL}/api/server/statistics
          headers:
            x-api-key: ${IMMICH_API_KEY}
            Accept: application/json
          template: |
            <div class="flex justify-between text-center">
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "photos" | formatNumber }}</div>
                  <div class="size-h6">PHOTOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "videos" | formatNumber }}</div>
                  <div class="size-h6">VIDEOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
                  <div class="size-h6">USAGE</div>
              </div>
            </div>

        - type: custom-api
          title: Cup Updates
          cache: 1h
          url: ${CUP_URL}/api/v3/json
          method: GET
          template: |
            {{ $defaultServerName := "Glance" }}  {{/* Set your default server name here */}}
            {{ $showUpdateKind := true }}  {{/* Toggle this to false to hide the Update Kind row */}}
            {{ $filterInactiveImages := true }}  {{/* Set to false to stop filtering unused images */}}

            <style>
              .vertical-separator-cup {
                width: 3px;
                height: 3.5rem;
                margin: 0 1rem;
                border-radius: 2px;
                align-self: center;
                background: linear-gradient(to bottom, transparent, rgba(255,255,255,0.05) 20%, rgba(255,255,255,0.05) 80%, transparent);
              }
              .container-list-cup li {
                text-align: center;
                margin-top: 1.5rem;
              }
              .container-list-cup {
                padding: 0;
                margin: 0;
                line-height: 1.2;
              }
              .container-list-cup a {
                text-decoration: none;
                display: block;
                padding: 1px 0;
                font-size: 1.1rem;
                margin-top: 1rem;
              }
              .status-values-cup {
                font-size: 1.8rem;
              }
            </style>

            <div class="flex flex-column gap-4">
              <div class="flex items-center text-center">
                <div class="flex-1">
                  <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.monitored_images" }}</div>
                  <div class="size-h6">TOTAL</div>
                </div>
                <div class="vertical-separator-cup"></div>
                <div class="flex-1">
                  <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.up_to_date" }}</div>
                  <div class="size-h6">UP TO DATE</div>
                </div>
                <div class="vertical-separator-cup"></div>
                <div class="flex-1">
                  <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.updates_available" }}</div>
                  <div class="size-h6">AVAILABLE</div>
                </div>
              </div>

              {{ if $showUpdateKind }}
                <div class="flex items-center text-center" style="margin-top: 1rem;">
                  <div class="flex-1">
                    <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.major_updates" }}</div>
                    <div class="size-h6">MAJOR</div>
                  </div>
                  <div class="vertical-separator-cup" style="width: 2px; margin: 0 0.25rem;"></div>
                  <div class="flex-1">
                    <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.minor_updates" }}</div>
                    <div class="size-h6">MINOR</div>
                  </div>
                  <div class="vertical-separator-cup" style="width: 2px; margin: 0 0.25rem;"></div>
                  <div class="flex-1">
                    <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.patch_updates" }}</div>
                    <div class="size-h6">PATCH</div>
                  </div>
                  <div class="vertical-separator-cup" style="width: 2px; margin: 0 0.25rem;"></div>
                  <div class="flex-1">
                    <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.other_updates" }}</div>
                    <div class="size-h6">DIGEST</div>
                  </div>
                  <div class="vertical-separator-cup" style="width: 2px; margin: 0 0.25rem;"></div>
                  <div class="flex-1">
                    <div class="status-values-cup size-h3">{{ .JSON.Int "metrics.unknown_updates" }}</div>
                    <div class="size-h6">UNKNOWN</div>
                  </div>
                </div>
              {{ end }}

              <div class="container-list-cup">
                <ul class="list list-gap-10-cup collapsible-container" data-collapse-after="3">
                  {{ $hasUpdates := false }}
                  {{ range .JSON.Array "images" }}
                    {{ $inUse := .Bool "in_use" }}
                    {{ if or (not $filterInactiveImages) $inUse }}
                      {{ if .Bool "result.has_update" }}
                        {{ $hasUpdates = true }}
                        <li>
                          {{ $registry := .String "parts.registry" }}
                          {{ $repository := .String "parts.repository" }}
                          {{ $url := "#" }}

                          {{ if eq $registry "registry-1.docker.io" }}
                            {{ $url = printf "https://hub.docker.com/r/%s" $repository }}
                          {{ else if eq $registry "ghcr.io" }}
                            {{ $url = printf "https://github.com/%s" $repository }}
                          {{ else if eq $registry "lscr.io" }}
                            {{ if .String "url" }}
                              {{ $url = .String "url" }}
                            {{ else }}
                              {{ $url = printf "https://fleet.linuxserver.io/%s" $repository }}
                            {{ end }}
                          {{ end }}

                          <a class="block text-truncate" href="{{ $url }}" target="_blank" rel="noreferrer" style="font-size: 1.47rem;">{{ $repository }}</a>

                          {{ $currentVersion := .String "result.info.current_version" }}
                          {{ $newVersion := .String "result.info.new_version" }}
                          {{ $localDigests := .Array "result.info.local_digests" }}
                          {{ $remoteDigest := .String "result.info.remote_digest" }}
                          {{ $serverName := .String "server" }}

                          {{ if or (eq $serverName "") (eq $serverName "null") (not $serverName) }}
                            {{ $serverName = $defaultServerName }}
                          {{ end }}

                          <div style="margin: 0.5rem 0; font-size: 1.28rem; color: #6c757d;">
                            Server: {{ $serverName }}
                          </div>

                          {{ if and $currentVersion $newVersion }}
                            <div style="margin: 0.2rem 0;">
                              <span>{{ $currentVersion }}</span>
                              <span> → </span>
                              <span class="size-h4 color-positive">{{ $newVersion }}</span>
                            </div>
                          {{ end }}

                          {{ if $localDigests }}
                            {{ $digest := index $localDigests 0 }}
                            {{ $digestStr := printf "%s" $digest }}
                            {{ $remoteDigestStr := printf "%s" $remoteDigest }}

                            {{ $shortLocal := slice $digestStr 8 14 }}
                            {{ $shortRemote := slice $remoteDigestStr 7 13 }}

                            <div class="flex gap-10 justify-center items-center" style="margin-top: 0.5rem;">
                              <span>Dig: {{ $shortLocal }}</span>
                              <span>→</span>
                              <span class="size-h4">Dig: <span class="color-positive">{{ $shortRemote }}</span></span>
                            </div>
                          {{ end }}
                        </li>
                      {{ end }}
                    {{ end }}
                  {{ end }}

                  {{ if not $hasUpdates }}
                    <div class="flex items-center justify-center" style="margin-top: 1.5rem;">
                      <span class="color-positive size-h4">All images are up to date!</span>
                    </div>
                  {{ end }}
                </ul>
              </div>
            </div>

        - type: server-stats
          servers:
            - type: local
              name: "RadiantGarden"
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  hide: false
                "/app/raid":
                  hide: false
