glanceapp:
  templates: "roles/docker/glanceapp/templates"
  files: "roles/docker/glanceapp/files"
  volumes:
    root: "{{ docker.services_dir }}/glanceapp"
    config: "{{ docker.services_dir }}/glanceapp/config"
    assets: "{{ docker.services_dir }}/glanceapp/assets"
  ports:
    http: 9000
