glanceapp:
  templates: "roles/docker/glanceapp/templates"
  files: "roles/docker/glanceapp/files"
  volumes:
    root: "{{ storage.docker }}/glanceapp"
    config: "{{ storage.docker }}/glanceapp/config"
    assets: "{{ storage.docker }}/glanceapp/assets"
  ports:
    http: 9000
